### ISSUE TITLE
is it possible to have kafka connect or ksqldb native image ?

### ISSUE THREAD

**Issue by rjdp** [ozangunalp/kafka-native#173]
I am looking to reduce resource usage of my kafka connect workers, i use it via the embedded connect in ksqldb or the kafka connect directly. Let me know your thoughts. I understand that this question is not relevant to this project but since its related am curious to understand you opinion.

**Comment by ozangunalp** [comment]
Hi,

Kafka Connect is a server with a bunch of runtime-loaded plugins, it would not be feasible to produce a native binary out of it.

**Comment by rjdp** [comment]
got it, Thanks for the reply.
