### ISSUE TITLE
BrokerConfig.defaultCoreConfig sometimes gets in the way

### ISSUE THREAD

**Issue by k-wall** [ozangunalp/kafka-native#2]
The opinionated nature of `BrokerConfig.defaultCoreConfig` sometimes gets in the way of some use-cases.

For instance, when bringing up a multi node kraft based cluster  a configuration with 1 broker being in the `controller,broker` and the second being only a `broker` gives a substantial start-up saving over two brokers in the `controller,broker` role (controller leader election avoided).  It is currently impossible to configure a broker in the broker only role - `defaultCoreConfig` turns it into a controller.

A simple way to avoid the problem is to allow the `defaultCoreConfig` to be skipped by config property. I'd default this to false maintaining current behaviour.   Alternatively, we could have a much richer set of flags, but to my mind, this would tend towards a re-expression of `server.properties` file itself - which would be pointless.

What do you think @ozangunalp ?

**Comment by ozangunalp** [comment]
I definitely agree that it might get in the way, as it isn't properly tested. I think it is still useful to have something "smart" to come up with a working broker configuration when `advertised.listeners` is given. IIRC most properties set in `BrokerConfig.defaultCoreConfig` don't override any existing config given via `server.properties` or app config properties – note the usage of `Map.putIfAbsent`. 

If there is a case you can't set up let's write a test in `BrokerConfigTest` and make it possible and intuitive to configure.
