### ISSUE TITLE
Support for Kraft mode

### ISSUE THREAD

**Issue by patpatpat123** [ozangunalp/kafka-native#249]
First of all, wanted to say big THANKS for this initiative.
This project is easy to use, easy to understand.

I am using this image, compared with regular kafka, and observed many advantages.

Just wanted to reach out asking for an enhancement request.

Kafka supports Kraft mode (zookeeper-less)
While this project supports native, it seems not to support Kaft.

Would it be possible for this project to support Kraft mode on top of native?

Thank you

**Comment by k-wall** [comment]
> Would it be possible for this project to support Kraft mode on top of native?

It does support KRafft already, that's it is default behaviour.

See: https://github.com/ozangunalp/kafka-native?tab=readme-ov-file#configuring-the-kafka-broker

**Comment by patpatpat123** [comment]
THANKS!
