### ISSUE TITLE
How to start a compiled binary program

### ISSUE THREAD

**Issue by iwanlebron** [ozangunalp/kafka-native#74]
[root@vm-3-20 ~]# ./kafka-server-amd64 -Dkafka.advertised.listeners=inside://:9093,outside://172.24.3.20:9092 -Dkafka.listeners=BROKER://:9093,PLAINTEXT://:9092,CONTROLLER://:9094 -Dkafka.inter.broker.listener.name=inside -Dkafka.controller.listener.names=CONTROLLER -Dkafka.listener.security.protocol.map=CONTROLLER:PLAINTEXT,inside:PLAINTEXT,outside:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL -Dkafka.inter.broker.listener.name=inside -Dkafka.process.roles=broker,controller

The error is as follows：
2023-06-20 17:04:26,601 WARN  [com.oza.kaf.ser.BrokerConfig] (main) Broker configs controller.listener.names, listeners, inter.broker.listener.name, listener.security.protocol.map will not be configured automatically, make sure to provide necessary configuration manually.
2023-06-20 17:04:26,605 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.IllegalArgumentException: No security protocol defined for listener BROKER

**Comment by ozangunalp** [comment]
I haven't tested your config but Kafka config validation says that you need to set the security protocol for the BROKER listener.

**Comment by ivanlebron** [comment]
How can I start so that other servers can access kafka?

**Comment by ivanlebron** [comment]
How can I start the binary kafka so that other servers can access it?

**Comment by ozangunalp** [comment]
I've some docker compose examples with multiple brokers using kafka-native. I can push them later in the evening.

**Comment by ivanlebron** [comment]
Okay, remind me when pushing.

**Comment by ozangunalp** [comment]
Here are an example with Kraft and another with zookeeper: https://github.com/ozangunalp/kafka-native/blob/main/docker-compose.yml and https://github.com/ozangunalp/kafka-native/blob/main/docker-compose-zk.yml

**Comment by ivanlebron** [comment]
I can easily build a Kafka cluster using Docker, but Kafka cannot be accessed from other servers.
