### ISSUE TITLE
Multi-arch support?

### ISSUE THREAD

**Issue by k-wall** [ozangunalp/kafka-native#78]
Would it  be possible to adapt the build to produce kafka and zookeeper native images for other architectures (s390x, ppc64le etc) in addition to the amd64.

https://github.com/quarkusio/quarkus/issues/23281#issuecomment-1267378935 gives me hope that support is in place. 

I was also wondering if cross-compilation is possible is Quarkus/GraalVM? https://github.com/oracle/graal/issues/407 makes me think 'no'.

Question came up from this https://github.com/orgs/strimzi/discussions/8801

**Comment by ozangunalp** [comment]
Providing multi-arch images with amd64+aarch64 is on my to-do list. 
GraalVM has arm64 support and normally Qemu emulation for that arch works well on Github CI. 
But I don't think adding s390x or ppc64le is feasible any time soon.

**Comment by k-wall** [comment]
Thanks for the rely.

Just trying to understand a little about s390x and ppc64le.  With s390 is https://github.com/oracle/graal/issues/2980#issuecomment-726186683 still correct?  What the issue with ppc64le?

**Comment by ozangunalp** [comment]
As far as I understand everything related to s390 in https://github.com/oracle/graal/issues/2980#issuecomment-726186683 also applies for ppc64le. I was able to find this: https://wiki.openjdk.org/pages/viewpage.action?pageId=13041681
